name: Workflow issue manager

on:
  workflow_dispatch:
  push:
    branches:
      - main

  issue_comment:
    types: [created, edited, deleted]

jobs:
  issue_handler:
    if: github.event_name == 'issue_comment' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    env:
      TF_VAR_GH_APP_ID: ${{ vars.GH_APP_ID }}
      TF_VAR_GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
      TF_VAR_GH_APP_PRIVATE_KEY_PATH: ${{ secrets.GH_APP_PRIVATE_KEY }}
      TF_VAR_GH_APP_INSTALLATION_ORGANIZATION_ID: ${{ vars.GH_APP_INSTALLATION_ORGANIZATION_ID }}
      TF_VAR_GITHUB_ORGANIZATION: "0xHackerSpace"
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}
      TF_VAR_TF_TOKEN_APP_TERRAFORM_IO: ${{ secrets.TF_TOKEN_app_terraform_io }}
      TF_VAR_MAIN_DOMAIN: ${{ vars.MAIN_DOMAIN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # # Log issue event (only for issue/issue_comment events)
      # - name: Log issue event
      #   if: github.event_name == 'issues' || github.event_name == 'issue_comment'
      #   run: |
      #     echo "Issue ${{ github.event.action }} by ${{ github.actor }}"
      #     echo "Issue title: ${{ github.event.issue.title }}"
      #     echo "Issue number: ${{ github.event.issue.number }}"
      #     echo "Issue body: ${{ github.event.issue.body }}"

      # Install Terraform
      - name: Setup Terraform
        if: github.event_name == 'push'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"
          cli_config_credentials_token: ${{ secrets.TF_TOKEN_app_terraform_io }};

      # Terraform login
      # - name: Terraform login (HCP via token)
      #   if: github.event_name == 'push'
      #   env:
      #     TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}
      #   run: terraform login
      #   working-directory: ./state

      # Terraform init
      - name: Terraform init
        if: github.event_name == 'push'
        run: terraform init
        working-directory: ./state

      # Terraform plan
      - name: Terraform plan
        if: github.event_name == 'push'
        run: terraform plan
        working-directory: ./state
      # Terraform apply
      - name: Terraform apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve
        working-directory: ./state


  bash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install azure-ai-inference
      - name: Run bash script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_AI_MODELS }}
        shell: python
        run: |
          import os
          from azure.ai.inference import ChatCompletionsClient
          from azure.ai.inference.models import SystemMessage, UserMessage
          from azure.core.credentials import AzureKeyCredential

          endpoint = "https://models.github.ai/inference"
          model = "openai/gpt-5"
          token = os.environ['GITHUB_TOKEN']

          client = ChatCompletionsClient(
              endpoint=endpoint,
              credential=AzureKeyCredential(token),
          )

          response = client.complete(
              messages=[
                  SystemMessage("You are a helpful assistant."),
                  UserMessage("What is the capital of France?"),
              ],
              model=model
          )

          print(response.choices[0].message.content)

