name: Workflow issue manager

on:
  issues:
    types: [opened, edited, closed, reopened, assigned, unassigned]

jobs:
  issue_handler:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    env:
      TF_VAR_GH_APP_ID: ${{ vars.GH_APP_ID }}
      TF_VAR_GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
      TF_VAR_GH_APP_PRIVATE_KEY_PATH: ${{ secrets.GH_APP_PRIVATE_KEY }}
      TF_VAR_GH_APP_INSTALLATION_ORGANIZATION_ID:  ${{ vars.GH_APP_INSTALLATION_ORGANIZATION_ID }}
      TF_VAR_GITHUB_ORGANIZATION: "0xHackerSpace"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log issue event
        run: |
          echo "Issue ${{ github.event.action }} by ${{ github.actor }}"
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Issue body: ${{ github.event.issue.body }}"

      - name: terraform-config
        uses: ./.github/actions/tf-config
        with:
          terraform_version: "1.5.0"
          working_directory: "./state"
      - name: terraform plan
        working-directory: "./state"
        run: terraform plan